blog/urls.py
from django.urls import path, re_path
from . import views
app_name = "post"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addpost/',views.addPost,name = "addpost"),
    path('post/<slug:slug>/',views.post_detail,name = "post_detail"),
    path('update/<slug:slug>',views.updatePost,name = "update"),
    path('delete/<slug:slug>',views.deletePost,name = "delete"),
    path('',views.posts,name = "posts"),
    path('comment/<slug:slug>',views.addComment,name = "comment"),
    path('post/<slug:slug>/preference/<int:userpreference>', views.postpreference, name='preference')
   ]

blogpost/urls.py
from django.contrib import admin
from django.urls import path, include

from user import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.loginUser,name = "login"),
    path('about/',views.about,name = "about"),
    path('blogs/',include("blog.urls")),
    path('user/',include("user.urls")),
    path('index/', views.index, name="index")

]

user/urls.py
from django.contrib import admin
from django.urls import path
from .views import RegisterView, loginUser, logoutUser, index, ActivateAccount

app_name = "user"

urlpatterns = [
    path('register/',RegisterView.as_view(),name = "register"),
    path('login/',loginUser,name = "login"),
    path('logout/',logoutUser,name = "logout"),
     path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.template.defaultfilters import slugify

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = RichTextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes=models.IntegerField(default=0)
    dislikes=models.IntegerField(default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.title)
        return super(Post, self).save(*args, **kwargs)
    
VALUE= (
    (1,"Like"),
    (2,"Dislike")
)

class Preference(models.Model):
    user= models.ForeignKey(User, on_delete= models.CASCADE)
    post= models.ForeignKey(Post, on_delete= models.CASCADE)
    value= models.IntegerField(choices=VALUE) #1: like 2: dislike
    date= models.DateTimeField(auto_now= True)
    
    def __str__(self):
        return str(self.user) + ':' + str(self.post) +':' + str(self.value)

    class Meta:
       unique_together = ("user", "post", "value")     


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete = models.CASCADE,related_name="comments")
    comment_author = models.ForeignKey(User, on_delete= models.CASCADE)
    comment_content = models.CharField(max_length = 200)
    comment_date = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

templates/about.html
{% extends "base.html" %}


{% block content %}
<link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<style>
  @import url(https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700);

*, *:after, *:before {
    margin: 0;
    padding: 0;

    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;

    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    font-smooth: always;

    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;

    font-family: inherit;

    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}

body {
    position: relative;
    background: #eeeeec;
    height: 100vh;
    text-align: center;
  /*background: #3f51b5;*/

  background: url('https://i.pinimg.com/474x/f8/1e/aa/f81eaafae688f5e319b99fdbcafdf22d.jpg') no-repeat center center;
  background-size: cover;
}
body:after{
  content: "";
  display: block;
  width: 100%;
  height: 100%;
  position: absolute;
  left: 0;
  top: 0;
  background-color: rgba(0,0,0,.5);
  z-index: -1
}

ul{
    list-style: none;
}

img {
    -ms-interpolation-mode: bicubic;
    vertical-align: middle;
    border: 0;
}

.profile-card{
  width: 300px;
  border-radius: 2px;
  overflow: hidden;
  box-shadow: 0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12);
  position: relative;
  margin: auto;
  background: rgba(255,255,255,1);
  top: 50%;
  transform: translateY(-50%);
}

.profile-card header{
  display: block;
  position: relative;
  background: rgba(255,255,255,1);
  text-align: center;
  padding: 30px 0 20px;
  z-index: 1;
  overflow: hidden;
}

.profile-card header:before{
  content: "";
  position: absolute;
  background: url('http://ali.shahab.pk/blur.php?img=http://ali.shahab.pk/ali-shahab.jpg&x=60') no-repeat;
  background-size: cover;
  width: 100%;
  height: 100%;
  left: 0;
  top: 0;
  z-index: -1;
  
}

.profile-card header:after{
  content: "";
  position: absolute;
  bottom: -1px;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: -1;
  background-image: linear-gradient(
      to bottom,
      rgba(255, 255, 255, 0) 0%,
      rgba(255, 255, 255, 1) 100%
  );
}

.profile-card header img{
  border-radius: 100%;
  overflow: hidden;
  width: 150px;
  /*border: 1px solid rgba(255,255,255,.5);*/
  box-shadow: 0 1px 0 rgba(0,0,0,.1),0 1px 2px rgba(0,0,0,.1);
}

.profile-card header h1{
  font-weight: 200;
  font-size: 42px;
  color: #444;
  letter-spacing: -3px;
  margin: 0;
  padding: 0;
}

.profile-card header h2{
  font-weight: 400;
  font-size: 14px;
  color: #666;
  letter-spacing: .5px;
  margin: 0;
  padding: 0;
}

.profile-card .profile-bio{
  padding: 0 30px;
  text-align: center;
  color: #888;
}

.profile-card .profile-social-links{
  display: table;
  width: 70%;
  margin: 20px auto;
}

.profile-card .profile-social-links li{
  display: table-cell;
  width: 33.3333333333333333%
}

.profile-card .profile-social-links li a{
  display: block;
  text-align: center;
  padding: 10px;
  margin: 0 10px;
  border-radius: 100%;
  -webkit-transition: box-shadow 0.2s;
  -moz-transition: box-shadow 0.2s;
  -o-transition: box-shadow 0.2s;
  transition: box-shadow 0.2s;
}
.profile-card .profile-social-links li a:hover{
  box-shadow: 0 1px 1.5px 0 rgba(0,0,0,.12),0 1px 1px 0 rgba(0,0,0,.24);
}

.profile-card .profile-social-links li a:active{
  box-shadow: 0 4px 5px 0 rgba(0,0,0,.14),0 1px 10px 0 rgba(0,0,0,.12),0 2px 4px -1px rgba(0,0,0,.2);
}

.profile-card .profile-social-links li a img{
  width: 100%;
  display: block;
}
</style>
<aside class="profile-card">
  
  <header>
    
   
    <a href="https://asthavarshneyy.netlify.app/">
      <img src="https://media.licdn.com/dms/image/C4D03AQFCOsWrOuLbeQ/profile-displayphoto-shrink_400_400/0/1654486264886?e=1683158400&v=beta&t=NuocTzsV9i4oZoXADpdfQqIWPwzBhPe6WS7GzaGISx8">
    </a>

    <!-- the username -->
    <h1>Astha Varshney</h1>
    
    <h2>Full- Stack Web Developer</h2>
    
  </header>
  
 
  <div class="profile-bio">
    
    <p>Tech Stack used- Django, PostgreSQL, HTML5, CSS
  </div>
  
 
  <ul class="profile-social-links">
    
   
    <li>
      <a href="https://twitter.com/asthavarshney2"> <i class="fa fa-twitter"></i></a>
    </li>
    
   
    <li>
      <a href="https://github.com/asthavarshneyy"><i class="fa fa-github"></i></a>
    </li>
    
    
    <li>
      <a href="https://www.linkedin.com/in/astha-varshney-132980191/"><i class="fa fa-linkedin"></i></a>
    </li>
    
    
    
  </ul>
  
</aside>

{% endblock content %}

templates/account_activation_email.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration:

http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}  
{% endautoescape %} 

templates/addpost.html
{% extends "layout.html" %}

{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Start a new Post</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Create</button>
        </form>
    </div>
  </div>


{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Astha Varshney</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            * {
                padding: 4px; 
                box-sizing: border-box;
              }

            body {
            /* font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd; */
            width: 100%;
            height: 100vh;
            /* display: flex; */
            /* position: relative;  */
            background: #eeeeec;
            align-items: center;
            flex-direction: column;
            justify-content: center;
            
            font-family: 'Open Sans', sans-serif;
            font-size: 100%;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>
    <script>
        function aboutdeveloper() {
            window.open("https://linktr.ee/asthavarshney", "_top");
        }
    </script>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                    
                    {% if request.user.is_authenticated %}
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item text-black">
                                <a class="nav-link text-black font-weight-bold" href="{%url 'about' %}">About</a>
                        </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{%url 'post:posts' %}">Posts</a>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{%url 'post:dashboard' %}">Dashboard</a>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{%url 'user:logout' %}">Logout</a>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav> 
        
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Created by Astha Varshney</p>
        </footer>
    </body>
</html>

templates/dashboard.html
{% extends "base.html" %}

{% block content %}
<hr>
<h3>
    Welcome, <small>{{request.user.username}}
</h3>
<hr>
<a class = "btn btn-danger" href = "{% url 'post:addpost' %}">Start a new Post </a>
<hr>
{% if posts %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Created on</th>
            <th scope="col">Status</th>
            <th scope="col">Last updated on</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for post in posts %}
          <tr>
            <td><a href="{% url 'post:post_detail' post.slug %}">{{post.title}}</a></td>
            <td>{{post.author}}</td>
            <td>{{post.created_on}}</td>
            <td>{{post.get_status_display}}</td>
            <td>{{post.updated_on}}</td>
            <td><a href="{% url 'post:update' post.slug %}" class = "btn btn-danger">Update</a></td>
            <td><a href="{% url 'post:delete' post.slug %}" class = "btn btn-danger">Delete</a> </td>
              
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
<!-- <table class="table">
  <thead>
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Created on</th>
        <th scope="col">Last updated on</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
  </thead>
</table> -->
{% else %}

<div class = "alert alert-danger">
    You don't have any post yet

</div>
{% endif %}

{% endblock content %}

templates/email.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title></title>
		<style>
			@import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900');
		</style>
	</head>
	<body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
		<div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
			<section style="margin: 0 15px;color:#425b76;">
				<h2 style="margin: 40px 0 27px 0;text-align: center;">Thank you to registration</h2>
				<hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
				<p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Hi {{username}}, we have received your details and will process soon.</p>
			</section>
		</div>
	</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white">Welcome to BlogPost by Astha Varshney</h3>
                </div>
            </div>
        </div>
    </div>
</header>


{%endblock%}

templates/login.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
       
        <hr>
        <form method = "post" novalidate>
            {% csrf_token %}
            <h2>Login</h2>
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Login</button>
            <p>Don't have an account? <button type="button">
                <a href="{% url 'user:register' %}">Register</a>
            </button></p>
        </form>
    </div>
  </div>

{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-10 offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{post.title}}</h3>

      <!-- Author -->
      <p class="lead">
        Published by {{post.author}} 
      </p>
      <hr>

      <!-- Date/Time -->
      <p>{{post.created_on}}</p>
      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{post.content|safe}}
      </p>

      <hr>

      <a href="#" onClick="document.getElementById('likebutton').submit()">Like</a> {{post.likes}}   |   <a href="#" onClick="document.getElementById('dislikebutton').submit()">Dislike</a> {{post.dislikes}}

      <form id="likebutton" method="POST" action="{% url 'post:preference' slug=post.slug userpreference=1 %}">
      {% csrf_token %}
      <input type="hidden">
      </form>

      <form id="dislikebutton" method="POST" action="{% url 'post:preference' slug=post.slug userpreference=2 %}">
      {% csrf_token %}
      <input type="hidden">
      </form>

      <hr>

      <h4>Comments {% if comments %}({{comments.count }}){% endif %}</h4>
      <hr>
      {% if comments %}
      {% for comment in comments  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{ comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}
          </div>
        </div>
      {% endfor %}
      
      
      {% else %}
      <div class ="alert alert-danger">
        There are no comments on this post, be the first to comment!
      </div>
      {% endif %}

      <div class="card my-4 container">
          <h5 class="card-header">Add Comment:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'post:comment' post.slug %}">
              {% csrf_token %}
              <!-- <div class="form-group">
                  <label for="formGroupExampleInput">Name</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="Enter your name">
              </div> -->
              <div class="form-group">
                  <label for="formGroupExampleInput">Comment</label>
                <textarea name = "comment_content" class="form-control" rows="3" placeholder="Add a comment"></textarea>
              </div>
              <button type="submit" class="btn btn-danger my-3">Comment</button>
            </form>
          </div>
      </div>
    </div>
        
</div>
{% endblock content %}

templates/posts.html
{% extends "base.html" %}

{% block content %}

<div class ="row">
    
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <h3>Posts</h3>
                <hr>
                </div>
        </div>
</div>
<div class ="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form>
                 {% csrf_token %} 
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Search...">
              <button type="submit" class="btn btn-danger">Search</button>
            </form>
      </div>
    </div>

</div>


{% if posts %}

{% for post in posts %}
<div class="row">
    <div class="col-md-10 offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <a href="{% url 'post:post_detail' post.slug %}"><h2 class="mt-4">{{post.title}}</h2></a> 
        
      <!-- Author -->
      <p class="lead">
        
       published by  {{post.author}} 
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{post.created_on}}</p>
      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{post.content|safe|truncatewords:50}}
      </p>

      <a href="{% url 'post:post_detail' post.slug %}" class ="btn btn-danger my-3">Continue reading -></a>
      <hr>
         
        </div>
      </div>
      </div>

{% endfor %}


{% else %}
<div class ="row">
    
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
<div class = "alert alert-danger">
   Post not found
</div>
</div>
</div>
</div>
{% endif %}

{% endblock content %}

templates/register.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
      
      <hr>
      <form method = "post">
          {% csrf_token %}
          <h3>Register</h3>
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type = "submit" class = "btn btn-danger">Submit</button>
          <p>Already have an account? <button type="button">
            <a href="{% url 'user:login' %}">Login</a>
        </button></p>
      </form>
  </div>
</div>

{% endblock content %}

templates/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This application is created using Django framework</p>
        <a href="https://www.linkedin.com/in/astha-varshney-132980191/"
           class="btn btn-danger">Know more about the developer</a>
    </div>
</div>
</div>

{% endblock sidebar %}

templates/update.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">submit</button>
        </form>
    </div>
  </div>


{% endblock content %}